config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :companies

  resources :uploads

  resources :staffs

  resources :divisions

  resources :assets do
     member do
        put :archived
     end

     collection do
        get :disposed
     end
  end 
  
  root 'assets#index'










end

app/models/staff.rb
class Staff < ActiveRecord::Base
	has_one :asset, foreign_key: 'verifier'
	belongs_to :division
	
	validates :id, :name, :address, :telephone_no,:division_id, presence:true	
	validates :id, uniqueness:true

		def self.search(search)
        	if search
            	 where('name LIKE ?', "%#{search}%")
         	else
            	 all
        	end
    	end
	
end

app/controllers/staffs_controller.rb
class StaffsController < ApplicationController
  before_filter :authenticate_user!, :except => [:show, :index]
  before_action :set_staff, only: [:show, :edit, :update, :destroy]
  helper_method :sort_column, :sort_direction

  respond_to :html

  def index
    @staffs = Staff.search(params[:search]).order(sort_column + " " + sort_direction).paginate(:per_page => 5, :page => params[:page])
    respond_with(@staffs)
  end

  def show
    respond_with(@staff)
  end

  def new
    @staff = Staff.new
    respond_with(@staff)
  end

  def edit
  end

  def create
    @staff = Staff.new(staff_params)
    @staff.save
    respond_with(@staff)
  end

  def update
    @staff.update(staff_params)
    respond_with(@staff)
  end

  def destroy
    @staff.destroy
    respond_with(@staff)
  end

  private
    def set_staff
      @staff = Staff.find(params[:id])
    end

    def staff_params
      params.require(:staff).permit(:id, :name, :address, :telephone_no, :division_id)
    end

     def sort_column
      Asset.column_names.include?(params[:sort]) ? params[:sort] : "name"
    end
  
    def sort_direction
      %w[asc desc].include?(params[:direction]) ? params[:direction] : "asc"
    end
end

app/helpers/staffs_helper.rb
module StaffsHelper
end

app/views/staffs/_form.html.erb
<%= form_for(@staff) do |f| %>
  <% if @staff.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@staff.errors.count, "error") %> prohibited this staff from being saved:</h2>

      <ul>
      <% @staff.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
<div class="row">
 <div class="col-lg-7">

 <div class="panel panel-default">
<div class="panel-body">
  <div class="field">
    <%= f.label :Staff_id, "Staff ID" %><br>
    <%= f.text_field :id %>
  </div>
  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :address %><br>
    <%= f.text_area :address %>
  </div>
  <div class="field">
    <%= f.label :telephone_no %><br>
    <%= f.text_field :telephone_no %>
  </div>
  <div class="field">
    <%= f.label :division_id %><br>
    <%= f.select(:division_id, Division.all.collect {|c| [ c.name, c.id ]}, :include_blank => true) %>
  </div>
  <div class="actions">
    <%= f.submit 'Save', :class => "btn btn-primary pull-left btn-sm " %>
  </div>
</div>
<%= link_to '<div class="glyphicon glyphicon-arrow-left"> Back</div>'.html_safe, staffs_path, :class => "btn btn-default pull-left" %>


</div>
</div>
</div>
<% end %>

app/views/staffs/edit.html.erb
<div>
	<h1 class="page_header">Edit Staff</h1>
</div>


<%= render 'form' %>

app/views/staffs/index.html.erb
<div>
                    <h1 class="page-header">Staff List</h1>
                </div>
                <!-- /.col-lg-12 -->
            </div>
            <!-- /.row -->
            <div class="row">
                <div class="col-lg-12">
                    <div class="panel panel-default">
                       <div class="panel-heading">
              <div class="row">
                <div class="col-md-6">
                <%=form_tag @staffs_path, :method => 'get' do %>
                <div class="input-group">
                  <input type="search" name="search" class="form-control" placeholder="Name search">
                  <span class="input-group-btn">
                      <button type="submit" class="btn btn-default" type="button" value="search"><div class="glyphicon glyphicon-search"></div></button>
                  </span>
                </div><!-- /input-group -->
                <% end %>
                </div>
                <%if params[:search] %><h6> Search result for : <%=params[:search]%></h6><% end %>
                <% if user_signed_in? %>
                <div class="col-md-6">
                <%= link_to 'Add Staff', new_staff_path, :class=>"btn btn-primary clearfix pull-right" %>
                </div>
                <% end %>
              </div>
            </div>
                                <div class="table-responsive">
                                <table class="table table-striped table-bordered table-hover" id="dataTables-example">
  <thead>
    <tr>
      <th><%= sortable "id", "Staff ID" %></th>
      <th>Name</th>
      <th>Address</th>
      <th>Telephone no</th>
      <th>Division</th>
      <th colspan="3">Actions</th>
    </tr>
  </thead>

  <tbody>
    <% @staffs.each do |staff| %>
      <tr>
        <td><%= staff.id %></td>
        <td><%= staff.name %></td>
        <td><%= staff.address %></td>
        <td><%= staff.telephone_no %></td>
        <td><%= staff.division_id %></td>
        <td><span class="has-tooltip" data-toggle="tooltip" title="Show"><span class="has-tooltip" data-toggle="tooltip" title="Show"><%= link_to '', staff, :class => "btn btn-primary btn-xs glyphicon glyphicon-file" %>
            <% if user_signed_in? %></span>
            <span class="has-tooltip" data-toggle="tooltip" title="Edit"><%= link_to '', edit_staff_path(staff), :class => "btn btn-primary btn-xs glyphicon glyphicon-edit" %></span>
            <span class="has-tooltip" data-toggle="tooltip" title="Delete"><%= link_to '', staff, method: :delete, data: { confirm: 'Are you sure?' }, :class => "btn btn-primary btn-xs glyphicon glyphicon-trash" %></span>
            <% end %>
            </td>
      </tr>
    <% end %>
  </tbody>
</table>
    </div>
    </div>
    </div>

<br>

app/views/staffs/new.html.erb
<div>
	<h1 class="page-header">New staff</h1>
</div>
<%= render 'form' %>

app/views/staffs/show.html.erb
<div class="row">
 <div class="col-lg-7">

 <div class="panel panel-default" id="the_show">


<div class="panel-heading">
<p>
  <strong>ID :</strong>
  <%= @staff.id %>
</p>
<p>
  <strong>Name:</strong>
  <%= @staff.name %>
</p>
</div>

<div class="panel-body">
<p>
  <strong>Address:</strong>
  <%= @staff.address %>
</p>

<p>
  <strong>Telephone no:</strong>
  <%= @staff.telephone_no %>
</p>

<p>
  <strong>Division:</strong>
  <%= @staff.division_id %>
</p>





<%= link_to 'Edit', edit_staff_path(@staff), :class => "btn btn-primary pull-left btn-sm "  %> 
</div>
<%= link_to '<div class="glyphicon glyphicon-arrow-left"> Back</div>'.html_safe, staffs_path, :class => "btn btn-default pull-left" %>


</div>
</div>
</div>