config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :companies

  resources :uploads

  resources :staffs

  resources :divisions

  resources :assets do
     member do
        put :archived
     end

     collection do
        get :disposed
     end
  end 
  
  root 'assets#index'










end

app/models/division.rb
class Division < ActiveRecord::Base
  	has_many :asset, dependent: :destroy
  	has_many :staff
    validates :id, :name, :description, presence: true
    validates :id, :name, uniqueness: true
    validates :id, numericality: true

    
    	def self.search(search)
        	if search
            	 where('name LIKE ?', "%#{search}%")
         	else
            	 all
        	end
    	end

end



 #t.string :name
    #  t.text :description

app/controllers/divisions_controller.rb
class DivisionsController < ApplicationController
  before_filter :authenticate_user!, :except => [:show, :index]
  before_action :set_division, only: [:show, :edit, :update, :destroy]
  helper_method :sort_column, :sort_direction

  # GET /divisions
  # GET /divisions.json
  def index
    @divisions = Division.search(params[:search]).order(sort_column + " " + sort_direction).paginate(:per_page => 5, :page => params[:page])
  end

  # GET /divisions/1
  # GET /divisions/1.json
  def show
  end

  # GET /divisions/new
  def new
    @division = Division.new
  end

  # GET /divisions/1/edit
  def edit
  end

  # POST /divisions
  # POST /divisions.json
  def create
    @division = Division.new(division_params)

    respond_to do |format|
      if @division.save
        format.html { redirect_to @division, notice: 'Division was successfully created.' }
        format.json { render :show, status: :created, location: @division }
      else
        format.html { render :new }
        format.json { render json: @division.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /divisions/1
  # PATCH/PUT /divisions/1.json
  def update
    respond_to do |format|
      if @division.update(division_params)
        format.html { redirect_to @division, notice: 'Division was successfully updated.' }
        format.json { render :show, status: :ok, location: @division }
      else
        format.html { render :edit }
        format.json { render json: @division.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /divisions/1
  # DELETE /divisions/1.json
  def destroy
    @division.destroy
    respond_to do |format|
      format.html { redirect_to divisions_url, notice: 'Division was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_division
      @division = Division.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def division_params
      params.require(:division).permit(:id, :name, :description)
    end

    def sort_column
      Asset.column_names.include?(params[:sort]) ? params[:sort] : "name"
    end
  
    def sort_direction
      %w[asc desc].include?(params[:direction]) ? params[:direction] : "asc"
    end
end

app/helpers/divisions_helper.rb
module DivisionsHelper
end

app/views/divisions/_form.html.erb
<%= form_for(@division) do |f| %>
  <% if @division.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@division.errors.count, "error") %> prohibited this division from being saved:</h2>

      <ul>
      <% @division.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

    <div class="row">
    <div class="col-lg-7">

      <div class="panel panel-default">
          <div class="panel-body">
          <div class="field">
            <%= f.label :Division_id, "Division ID" %><br>
            <%= f.text_field :id %>
         </div>
          <div class="field">
            <%= f.label :name %><br>
            <%= f.text_field :name %>
          </div>
          
          <div class="field">
            <%= f.label :description %><br>
            <%= f.text_area :description %>
          </div>
          <div class="actions">
            <%= f.submit 'Save', :class => "btn btn-primary pull-left btn-sm " %>
          </div>
            </div>
<%= link_to '<div class="glyphicon glyphicon-arrow-left"> Back</div>'.html_safe, companies_path, :class => "btn btn-default pull-left" %>


</div>
</div>
</div>
<% end %>

app/views/divisions/edit.html.erb
<h1>Editing division</h1>

<%= render 'form' %>

<%= link_to 'Show', @division %> |
<%= link_to 'Back', divisions_path %>

app/views/divisions/index.html.erb
                <div>
                    <h1 class="page-header">Division List</h1>
                </div>
                <!-- /.col-lg-12 -->
            </div>
            <!-- /.row -->
            <div class="row">
                <div class="col-lg-12">
                    <div class="panel panel-default">
                        <!-- /.panel-heading -->
                                     <div class="panel-heading">
              <div class="row">
                <div class="col-md-6">
                <%=form_tag @divisions_path, :method => 'get' do %>
                <div class="input-group">
                  <input type="search" name="search" class="form-control" placeholder="Name search">
                  <span class="input-group-btn">
                      <button type="submit" class="btn btn-default" type="button" value="search"><div class="glyphicon glyphicon-search"></div></button>
                  </span>
                </div><!-- /input-group -->
                <% end %>
                </div>
                <%if params[:search] %><h6> Search result for : <%=params[:search]%></h6><% end %>
                <% if user_signed_in? %>
                <div class="col-md-6">
                <%= link_to 'Add Division', new_division_path, :class=>"btn btn-primary clearfix pull-right" %>
                </div>
                <% end %>
              </div>
            </div>
                                <div class="table-responsive">
                                <table class="table table-striped table-bordered table-hover">
  <thead>
    <tr>
      <th><%= sortable "id", "Division ID" %></th>
      <th><%= sortable "name", "Name" %></th>
      <th>Description</th>
      <th colspan="3">Actions</th>
    </tr>
  </thead>

  <tbody>
    <% @divisions.each do |division| %>
      <tr>
        <td><%= division.id %></td>
        <td><%= division.name %></td>
        <td><%= division.description %></td>
          <td><span class="has-tooltip" data-toggle="tooltip" title="Show"><%= link_to '', division, :class => "btn btn-primary btn-xs glyphicon glyphicon-file" %></span>
            <% if user_signed_in? %>
              <span class="has-tooltip" data-toggle="tooltip" title="Edit"><%= link_to '', edit_division_path(division), :class => "btn btn-primary btn-xs glyphicon glyphicon-edit" %></span>
              <span class="has-tooltip" data-toggle="tooltip" title="Delete"><%= link_to '', division, method: :delete, data: { confirm: 'Are you sure?' }, :class => "btn btn-primary btn-xs glyphicon glyphicon-trash" %></span>
            <% end %>
            </td>
      </tr>
    <% end %>
  </tbody>
</table>
    </div>
    </div>
    </div>
<br>

</div>

app/views/divisions/new.html.erb
<div>
	<h1 class="page-header">New division</h1>
</div>
<%= render 'form' %>

app/views/divisions/show.html.erb
<div class="row">
 <div class="col-lg-7">
 
 <div class="panel panel-default" id="the_show">


<div class="panel-heading">
<p>
  <strong>ID :</strong>
  <%= @division.id %>
</p>
<p>
  <strong>Name:</strong>
  <%= @division.name %>
</p>

</div>

<div class="panel-body">

<p>
  <strong>Description:</strong>
  <%= @division.description %>
</p>

<%= link_to 'Edit', edit_division_path(@division), :class => "btn btn-primary pull-left btn-sm "  %> 
</div>
<%= link_to '<div class="glyphicon glyphicon-arrow-left"> Back</div>'.html_safe, divisions_path, :class => "btn btn-default pull-left" %>

</div>

</div>
</div>
</div>