config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :companies

  resources :uploads

  resources :staffs

  resources :divisions

  resources :assets do
     member do
        put :archived
     end

     collection do
        get :disposed
     end
  end 
  
  root 'assets#index'










end

app/models/company.rb
class Company < ActiveRecord::Base
    has_many :asset
    validates :id, :name, :description, presence: true
    validates :name, uniqueness:true
    validates :id, uniqueness: :true

    	def self.search(search)
        	if search
            	 where('name LIKE ?', "%#{search}%")
         	else
            	 all
        	end
    	end

end



# t.string :name
     # t.text :description

app/controllers/companies_controller.rb
class CompaniesController < ApplicationController
  before_filter :authenticate_user!, :except => [:show, :index]
  before_action :set_company, only: [:show, :edit, :update, :destroy]
  helper_method :sort_column, :sort_direction

  # GET /companies
  # GET /companies.json
  def index
    @companies = Company.search(params[:search]).order(sort_column + " " + sort_direction).paginate(:per_page => 5, :page => params[:page])
  end

  # GET /companies/1
  # GET /companies/1.json
  def show
  end

  # GET /companies/new
  def new
    @company = Company.new
  end

  # GET /companies/1/edit
  def edit
  end

  # POST /companies
  # POST /companies.json
  def create
    @company = Company.new(company_params)

    respond_to do |format|
      if @company.save
        format.html { redirect_to @company, notice: 'Company was successfully created.' }
        format.json { render :show, status: :created, location: @company }
      else
        format.html { render :new }
        format.json { render json: @company.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /companies/1
  # PATCH/PUT /companies/1.json
  def update
    respond_to do |format|
      if @company.update(company_params)
        format.html { redirect_to @company, notice: 'Company was successfully updated.' }
        format.json { render :show, status: :ok, location: @company }
      else
        format.html { render :edit }
        format.json { render json: @company.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /companies/1
  # DELETE /companies/1.json
  def destroy
    @company.destroy
    respond_to do |format|
      format.html { redirect_to companies_url, notice: 'Company was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_company
      @company = Company.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def company_params
      params.require(:company).permit(:id, :name, :description)
    end

    def sort_column
      Asset.column_names.include?(params[:sort]) ? params[:sort] : "name"
    end
  
    def sort_direction
      %w[asc desc].include?(params[:direction]) ? params[:direction] : "asc"
    end
end

app/helpers/companies_helper.rb
module CompaniesHelper
end

app/views/companies/_form.html.erb
<%= form_for(@company) do |f| %>
  <% if @company.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@company.errors.count, "error") %> prohibited this company from being saved:</h2>

      <ul>
      <% @company.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class="row">
    <div class="col-lg-7">

      <div class="panel panel-default">
        <div class="panel-body">
            <div class="field">
              <%= f.label :company_id, "Company ID" %><br>
              <%= f.text_field :id %>
            </div>
            <div class="field">
              <%= f.label :name %><br>
              <%= f.text_field :name %>
            </div>
            <div class="field">
              <%= f.label :description %><br>
              <%= f.text_area :description %>
            </div>
            <div class="actions">
              <%= f.submit 'Save', :class => "btn btn-primary pull-left btn-sm " %>
            </div>
            </div>
<%= link_to '<div class="glyphicon glyphicon-arrow-left"> Back</div>'.html_safe, companies_path, :class => "btn btn-default pull-left" %>


</div>
</div>
</div>
<% end %>

app/views/companies/edit.html.erb
<h1>Editing company</h1>

<%= render 'form' %>

<%= link_to 'Show', @company %> |
<%= link_to 'Back', companies_path %>

app/views/companies/index.html.erb
                <div>
                    <h1 class="page-header">Company List</h1>
                </div>
                <!-- /.col-lg-12 -->
            </div>
            <!-- /.row -->
            <div class="row">
                <div class="col-lg-12">
                    <div class="panel panel-default">
                        <!-- /.panel-heading -->
                         <div class="panel-heading">
              <div class="row">
                <div class="col-md-6">
                <%=form_tag @divisions_path, :method => 'get' do %>
                <div class="input-group">
                  <input type="search" name="search" class="form-control" placeholder="Name search">
                  <span class="input-group-btn">
                      <button type="submit" class="btn btn-default" type="button" value="search"><div class="glyphicon glyphicon-search"></div></button>
                  </span>
                </div><!-- /input-group -->
                <% end %>
                </div>
                <%if params[:search] %><h6> Search result for : <%=params[:search]%></h6><% end %>
                <% if user_signed_in? %>
                <div class="col-md-6">
                <%= link_to 'Add Company', new_company_path, :class=>"btn btn-primary clearfix pull-right" %>
                </div>
                <% end %>
                
              </div>
            </div>

                                <div class="table-responsive">
                                <table class="table table-striped table-bordered table-hover" id="dataTables-example">
  <thead>
    <tr>
      <th><%= sortable "id", "Company ID" %></th>
      <th><%= sortable "name", "Name" %></th>
      <th>Description</th>
      <th colspan="3">Actions</th>
    </tr>
  </thead>

  <tbody>
    <% @companies.each do |company| %>
      <tr>
        <td><%= company.id %></td>
        <td><%= company.name %></td>
        <td><%= company.description %></td>
          <td><span class="has-tooltip" data-toggle="tooltip" title="Show"><%= link_to '', company, :class => "btn btn-primary btn-xs glyphicon glyphicon-file" %></span>
            <% if user_signed_in? %>
            <span class="has-tooltip" data-toggle="tooltip" title="Edit"><%= link_to '', edit_company_path(company), :class => "btn btn-primary btn-xs glyphicon glyphicon-edit" %></span>
            <span class="has-tooltip" data-toggle="tooltip" title="Delete"><%= link_to '', company, method: :delete, data: { confirm: 'Are you sure?' }, :class => "btn btn-primary btn-xs glyphicon glyphicon-trash" %></span>
            <% end %>
            </td>
      </tr>
    <% end %>
  </tbody>
</table>
   </div>

    </div>
    </div>

<br>

app/views/companies/new.html.erb
<div>
	<h1 class="page-header">New company</h1>
</div>
<%= render 'form' %>

app/views/companies/show.html.erb
<div class="row">
 <div class="col-lg-7">

 <div class="panel panel-default" id="the_show">


<div class="panel-heading">
<p>
  <strong>ID :</strong>
  <%= @company.id %>
</p>
<p>
  <strong>Name:</strong>
  <%= @company.name %>
</p>
</div>
<div class="panel-body">
<p>
  <strong>Description:</strong>
  <%= @company.description %>
</p>



<%= link_to 'Edit', edit_company_path(@company), :class => "btn btn-primary pull-left btn-sm "  %> 
</div>
<%= link_to '<div class="glyphicon glyphicon-arrow-left"> Back</div>'.html_safe, companies_path, :class => "btn btn-default pull-left" %>


</div>
</div>
</div>