config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :companies

  resources :uploads

  resources :staffs

  resources :divisions

  resources :assets do
     member do
        put :archived
     end

     collection do
        get :disposed
     end
  end 
  
  root 'assets#index'










end

app/models/asset.rb
class Asset < ActiveRecord::Base
    has_many :uploads, :dependent => :destroy
    belongs_to :division

    accepts_nested_attributes_for :uploads,
        :allow_destroy => true,
        :reject_if     => :all_blank


    validates :finance_reference_id,:address,:subnumber,:division_id,:quantity,:company_id,:base_unit,
    :verifier,:asset_manufacturer,:print_date,:tag_date,:last_check,:asset_type,:acquisition_value,:current_value, presence: true
    
    validates :id, :subnumber,:acquisition_value,:current_value, numericality: true

    validates :id, uniqueness: :true

    def self.search(search)
        if search
             where('name  LIKE ?', "%#{search}%")
         else
             all
        end
    end

    
    
end


#t.string :name
    # t.text :description
     # t.text :address
     # t.integer :subnumber
     # t.boolean :archived
     # t.string :current_holder_id
     # t.string :division_id
     # t.integer :quantity
     # t.string :company_id
     # t.string :base_unit
     # t.string :verifier
     # t.string :asset_manufacturer
     # t.datetime :print_date
     # t.datetime :tag_date
     # t.datetime :last_check
     # t.string :asset_type
    #  t.decimal :acquisition_value
     # t.decimal :current_value

app/controllers/assets_controller.rb
class AssetsController < ApplicationController
    before_filter :authenticate_user!, :except => [:show, :index]
    before_action :set_asset, only: [:show, :edit, :update, :destroy]
    helper_method :sort_column, :sort_direction


  # GET /assets
  # GET /assets.json
  def index
        @assets = Asset.search(params[:search]).order(sort_column + " " + sort_direction).where(:archived => false).paginate(:per_page => 5, :page => params[:page])
  end



  # GET /assets/1
  # GET /assets/1.json
  def show
  end

  # GET /assets/new
  def new
    @asset = Asset.new
    @asset.uploads.build
  end


  # GET /assets/1/edit
  def edit
  end

  def disposed
    @assets = Asset.search(params[:search]).order(sort_column + " " + sort_direction).where(:archived => true).paginate(:per_page => 5, :page => params[:page])
    render action: :index
  end

  def archived

    @asset = Asset.find(params[:id])
    @asset.toggle!(:archived)

     respond_to do |format|
        if @asset.save
          format.html { redirect_to assets_url, notice: 'Asset archived' }
          format.js
        else
          format.html { redirect_to assets_url, notice: 'Unable to archived asset' }
          format.js
        end
     end
  end


  # POST /assets
  # POST /assets.json
  def create
    @asset = Asset.new(asset_params)
    respond_to do |format|
      if @asset.save
        format.html { redirect_to @asset, notice: 'Asset was successfully created.' }
        format.json { render :show, status: :created, location: @asset }
      else
        format.html { render :new }
        format.json { render json: @asset.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /assets/1
  # PATCH/PUT /assets/1.json
  def update
    respond_to do |format|
      if @asset.update(asset_params)
        format.html { redirect_to @asset, notice: 'Asset was successfully updated.' }
        format.json { render :show, status: :ok, location: @asset }
      else
        format.html { render :edit }
        format.json { render json: @asset.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /assets/1
  # DELETE /assets/1.json
  def destroy
    @asset.destroy
    respond_to do |format|
      format.html { redirect_to assets_url, notice: 'Asset was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_asset
      @asset = Asset.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def asset_params
      params.require(:asset).permit(:id, :finance_reference_id, :name, :description, :address, :subnumber, :archived, :current_holder_id, :division_id, :quantity, :company_id, :base_unit, :verifier, :asset_manufacturer, :print_date, :tag_date, :last_check, :asset_type, :acquisition_value, :current_value, { uploads_attributes: [ :file ]})
    end

    def sort_column
      Asset.column_names.include?(params[:sort]) ? params[:sort] : "name"
    end
  
    def sort_direction
      %w[asc desc].include?(params[:direction]) ? params[:direction] : "asc"
    end

end

app/helpers/assets_helper.rb
module AssetsHelper
end

app/views/assets/_form.html.erb
<% if @asset.errors.any? %>
    <div id="error_explanation" class="col-lg-12">
      <h2><%= pluralize(@asset.errors.count, "error") %> prohibited this asset from being saved:</h2>

      <ul>
      <% @asset.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
    
  <% end %>
<%= form_for(@asset) do |f| %>
<div class="col-lg-12">
<form class="form-horizontal">
  <div class="form-group">
     <%= f.label :Asset_id, class: "col-sm-4 control-label" %>
     <%= f.text_field :id, :size=>"40", placeholder: "Asset", class: "form-control" %>
  </div>
    
    
   
  <div class="form-group">
   <%= f.label :finance_reference_id, class: "col-sm-4 control-label" %>
   <%= f.text_field :finance_reference_id, :size=>"60", placeholder: "Financial Reference", class: "form-control" %>
  </div>
    
    
   
  <div class="form-group">
   <%= f.label :name, class: "col-sm-4 control-label" %>
   <%= f.text_field :name, :size=>"60", placeholder: "Name", class: "form-control" %>
  </div>
    
    
   
  <div class="form-group">
   <%= f.label :description, class: "col-sm-4 control-label" %>
   <%= f.text_area :description, :size=>"60", placeholder: "Desription", class: "form-control" %>
  </div>
    
    
   
  <div class="form-group">
   <%= f.label :address, class: "col-sm-4 control-label" %>
   <%= f.text_area :address, :size=>"60", placeholder: "Address", class: "form-control" %>
  </div>
    
    
   
  <div class="form-group">
   <%= f.label :subnumber, class: "col-sm-4 control-label" %>
   <%= f.number_field :subnumber, :size=>"60", class: "form-control" %>
  </div>
    
    
   
  <div class="form-group">
   <%= f.label :current_holder_id, class: "col-sm-4 control-label" %>
   <%= f.select(:current_holder_id, Staff.all.collect {|c| [ c.name, c.id ]}, :include_blank => true, class: "form-control" ) %>
  </div>
    
    <%= f.hidden_field :archived, :value => false %>
   
  <div class="form-group">
   <%= f.label :division_id, class: "col-sm-4 control-label" %>
   <%= f.select(:division_id, Division.all.collect {|c| [ c.name, c.id ]}, :include_blank => true, class: "form-control" ) %>
  </div>
    
    
   
  <div class="form-group">
   <%= f.label :quantity, class: "col-sm-4 control-label" %>
   <%= f.number_field :quantity, :size=>"60", class: "form-control" %>
  </div>
    
    
   
  <div class="form-group">
   <%= f.label :company_id, class: "col-sm-4 control-label" %>
   <%= f.select(:company_id, Company.all.collect {|c| [ c.name, c.id ]}, :include_blank => true, class: "form-control" ) %>
  </div>
    
    
   
  <div class="form-group">
   <%= f.label :base_unit, class: "col-sm-4 control-label" %>
   <%= f.text_field :base_unit, :size=>"60", placeholder: "Base unit", class: "form-control" %>
  </div>
    
    
   
  <div class="form-group">
   <%= f.label :verifier, class: "col-sm-4 control-label" %>
   <%= f.select(:verifier, Staff.all.collect {|c| [ c.name, c.id ]}, :include_blank => true, class: "form-control" ) %>
  </div>
    
    
   
  <div class="form-group">
   <%= f.label :asset_manufacturer, class: "col-sm-4 control-label" %>
   <%= f.text_field :asset_manufacturer, :size=>"60", placeholder: "Asset Manufacturer", class: "form-control" %>
  </div>
    
    
   
  <div class="form-group">
   <%= f.label :print_date, class: "col-sm-4 control-label" %>
   <%= f.datetime_select :print_date, class: "form-control" %>
  </div>
    
    
   
  <div class="form-group">
   <%= f.label :tag_date, class: "col-sm-4 control-label" %>
   <%= f.datetime_select :tag_date, class: "form-control" %>
  </div>
    
    
   
  <div class="form-group">
   <%= f.label :last_check, class: "col-sm-4 control-label" %>
   <%= f.datetime_select :last_check, class: "form-control" %>
  </div>
    
    
   
  <div class="form-group">
   <%= f.label :asset_type, class: "col-sm-4 control-label" %>
   <%= f.text_field :asset_type, :size=>"60", placeholder: "Asset Type", class: "form-control" %>
  </div>
    
    
   
  <div class="form-group">
   <%= f.label :acquisition_value, class: "col-sm-4 control-label" %>
   <%= f.text_field :acquisition_value, :size=>"60", placeholder: "Acquisition Value", class: "form-control" %>
  </div>
    
    
   
  <div class="field form-group">
   <%= f.label :current_value, class: "col-sm-4 control-label" %>
   <%= f.text_field :current_value, :size=>"60", placeholder: "Current value", class: "form-control" %>
  </div>
    
<br><br>

  <%= f.fields_for :uploads do |builder| %>
      <%= render 'upload_fields', :f => builder %>
  <% end %>
  <p><%= link_to_add_fields "Add File", f,:uploads %></p>
  
    
  <div class="actions">
    <%= f.submit %>
  </div>
</form>
</div>
<% end %>


app/views/assets/_upload_fields.html.erb
<div class="panel panel-default fields">
<p><%= f.file_field :file %></p>
<p><%= f.hidden_field :_destroy %></p>
<p><%= link_to_remove_fields "remove", f %></p>
   
</div>

app/views/assets/edit.html.erb

                <div class="col-lg-12">
                    <h1 class="page-header">Edit Asset</h1>
                </div>
                <!-- /.col-lg-12 -->
            </div>
<div class="row">
  <div class="col-lg-12">
                    <div class="panel panel-default">
                        <div class="panel-body">
                            <div class="row">
                                <div class="col-lg-6">
<%= render 'form' %>
 </div>  
                            </div>
                        </div>
  

<%= link_to 'Show', @asset %> |
<%= link_to 'Back', assets_path %>

app/views/assets/index.html.erb

        <div>
            <h1 class="page-header"><%if current_page?(disposed_assets_path) %>Disposed Asset List<% else %>Asset List<% end %></h1>
        </div>
                <!-- /.col-lg-12 -->
            <!-- /.row -->
      <div class="row">
        <div class="col-lg-12">
          <div class="panel panel-default">
          <!-- /.panel-heading -->
          <div class="panel-heading">
              <div class="row">
                <div class="col-md-6">
                <%=form_tag @assets_path, :method => 'get' do %>
                <div class="input-group">
                  <input type="search" name="search" class="form-control" placeholder="Name search">
                  <span class="input-group-btn">
                      <button type="submit" class="btn btn-default" type="button" value="search"><div class="glyphicon glyphicon-search"></div></button>
                  </span>

                </div><!-- /input-group -->
                <% end %>
                <%if params[:search] %><h6> Search result for : <%=params[:search]%></h6><% end %>
                <% if user_signed_in? %>
                </div>
                
                <div class="col-md-6">
                <%= link_to 'Add Asset', new_asset_path, :class=>"btn btn-primary clearfix pull-right" %>
                <%if current_page?(disposed_assets_path) %><%= link_to "Current Asset", assets_path %><% else %><%= link_to "Disposed Assets", disposed_assets_path %><% end %>
                </div>

                <% end %>
                
              </div>
            </div>
            
              <div class="table-responsive">
                <table class="table table-striped table-bordered table-hover">
                  <thead>
                    <tr>
                      <th><%= sortable "id", "ID" %></th>
                      <th><%= sortable "name", "Name" %></th>
                      <th>Description</th>
                      <th>Address</th>
                      <th><%= sortable "current_holder_id", "Current Holder ID" %></th>
                      <th><%= sortable "division_id", "Division ID" %></th>
                      <th>Quantity</th>
                      <th><%= sortable "last_check", "Last Check" %></th>
                      <th><%= sortable "asset_type", "Asset Type" %></th>

                      <th colspan="3"> Actions</th>
                    </tr>
                </thead>

                <tbody>
                  <% @assets.each do |asset| %>
                  <tr>
                   <td><%= asset.id %></td>
                   <td><%= asset.name %></td>
                   <td><%= asset.description %></td>
                   <td><%= asset.address %></td>
                   <td><% if asset.current_holder_id.present? %><%= link_to asset.current_holder_id, staff_path(asset.current_holder_id)  %><% end %></td>
                   <td><%= link_to asset.division_id, division_path(asset.division_id)  %></td>
                   <td><%= asset.quantity %></td>
                   <td><%= asset.last_check %></td>
                   <td><%= asset.asset_type %></td>
                      
                  <td><span class="has-tooltip" data-toggle="tooltip" title="Show"><%= link_to '', asset, :class => "btn btn-primary btn-xs glyphicon glyphicon-file" %></span>
                  <% if user_signed_in? %>
                      <span class="has-tooltip" data-toggle="tooltip" title="Edit"><%= link_to '', edit_asset_path(asset), :class => "btn btn-primary btn-xs glyphicon glyphicon-edit" %></span>
                      <span class="has-tooltip" data-toggle="tooltip" title="Delete"><%= link_to '', asset, method: :delete, data: { confirm: 'Are you sure?' }, :class => "btn btn-primary btn-xs glyphicon glyphicon-trash" %></span>
                          
                      <%if current_page?(disposed_assets_path) %>
                          <span class="has-tooltip" data-toggle="tooltip" title="Undispose"><%= link_to '', archived_asset_path(asset), data: { confirm: 'Are you sure?' }, :class => "btn btn-primary btn-xs glyphicon glyphicon-import", :method => :put  %></span>
                          <% else %>
                          <span class="has-tooltip" data-toggle="tooltip" title="Dispose"><%= link_to '', archived_asset_path(asset), data: { confirm: 'Are you sure?' }, :class => "btn btn-primary btn-xs glyphicon glyphicon-export", :method => :put  %><% end %></span>
                  <% end %>
                  </td>

                </tr>
               <% end %>
               </tbody>
                </table>
              </div>

        </div>
        <div class="pull-right"> 
          <%= will_paginate @assets, renderer: BootstrapPagination::Rails%>
        </div>
        </div>
      </div>
<br>



app/views/assets/new.html.erb

                <div class="col-lg-12">
                    <h1 class="page-header">New Asset</h1>
                </div>
                <!-- /.col-lg-12 -->
            </div>
  <div class="row">
  <div class="col-lg-12">
                    <div class="panel panel-default">
                        <div class="panel-body">
                            <div class="row">
                                <div class="col-lg-6">
<%= render 'form' %>
  </div>  
                            </div>
                        </div>
  

<%= link_to 'Back', assets_path %>

app/views/assets/show.html.erb
<div class="row">
 <div class="col-lg-7">

 <div class="panel panel-default" id="the_show">


<div class="panel-heading">
<p>
  <strong>ID :</strong>
  <%= @asset.id %>
</p>
<p>
  <strong>Name:</strong>
  <%= @asset.name %>
</p>
</div>
<div class="panel-body">


<p>
  <strong>Finance Reference ID:</strong>
  <%= @asset.finance_reference_id %>
</p>
<p>
  <strong>Description:</strong>
  <%= @asset.description %>
</p>
<p>
  <strong>Address:</strong>
  <%= @asset.address %>
</p>
<p>
  <strong>Subnumber:</strong>
  <%= @asset.subnumber %>
</p>
<p>
  <strong>Archived:</strong>
  <%= @asset.archived %>
</p>
<p>
  <strong>Current Holder ID:</strong>
  <%= @asset.current_holder_id %>
</p>
<p>
  <strong>Division ID:</strong>
  <%= @asset.division_id %>
</p>
<p>
  <strong>Quantity:</strong>
  <%= @asset.quantity %>
</p>
<p>
  <strong>Company ID:</strong>
  <%= @asset.company_id %>
</p>
<p>
  <strong>Base Unit:</strong>
  <%= @asset.base_unit %>
</p>
<p>
  <strong>Verifier ID:</strong>
  <%= @asset.verifier %>
</p>
<p>
  <strong>Asset Manufacturer:</strong>
  <%= @asset.asset_manufacturer %>
</p>
<p>
  <strong>Print Date:</strong>
  <%= @asset.print_date %>
</p>
<p>
  <strong>Tag Date:</strong>
  <%= @asset.tag_date %>
</p>
<p>
  <strong>Last Check:</strong>
  <%= @asset.last_check %>
</p>
<p>
  <strong>Asset Type:</strong>
  <%= @asset.asset_type %>
</p>
<p>
  <strong>Acquisition value:</strong>
  <%= @asset.acquisition_value %>
</p>
<p>
  <strong>Current value:</strong>
  <%= @asset.current_value %>
</p>

<p>

</p>

  <table class="table">
    <tr>
      <td> Filename </td>
      <td colspan="2"> Actions </td>

    </tr>
  <% @asset.uploads.each do |upload| %>
    <tr>
        <td><%= upload.filename %></td>
        <td><%= button_to 'Download', upload, method: :get %></td>
        <% if user_signed_in? %>
          <td><%= button_to 'Destroy', upload, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <% end %>
    </tr>
  <% end %> 
  </table>

  <% if user_signed_in? %>
<%= link_to 'Edit', edit_asset_path(@asset), :class => "btn btn-primary pull-left btn-sm "  %> 
  <% end %>
</div>
<%= link_to '<div class="glyphicon glyphicon-arrow-left"> Back</div>'.html_safe, assets_path, :class => "btn btn-default pull-left" %>


</div>
</div>
</div>